name: Docker Cleanup

on: 
    pull_request:
        types: [closed]

jobs:
    get_tags:
        runs-on: ubuntu-latest
        steps:
            - run: echo '${{ toJson(github) }}'
            - name: Cleanup
              run: |
                HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{secrets.DOCKER_USERNAME}}\", \"password\": \"${{secrets.DOCKER_PASSWORD}}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
                curl -i -X DELETE \
                  -H "Accept: application/json" \
                  -H "Authorization: JWT $HUB_TOKEN" \
                  https://hub.docker.com/v2/repositories/slushpupie/test_docker_image/tags/pr-${{ github.event.issue.number }}/
