name: Build PR Image

on: issue_comment

jobs:
  build:
    runs-on: ubuntu-latest

    ## 
    ##
    ## if: github.event.issue.pull_request && contains(github.event.comment.body, '/build-docker-image') && github.event.comment.author_association == 'MEMBER'
    ##
    ##
    ##
    
    steps:
      
      - run: echo '${{ toJson(github) }}'
      - run: echo '${{ toJson(inputs) }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: slushpupie/test_docker_image
          tags: |
            type=ref,event=pull_request
            type=sha

      - run: echo '${{ toJson(steps) }}'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


